# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-02-22 09:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publisherapi', '0003_auto_20210222_1508'),
    ]

    operations = [
        migrations.CreateModel(
            name='API',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api', models.CharField(max_length=25)),
                ('api_parameters', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='publisher',
            name='api',
        ),
        migrations.RemoveField(
            model_name='publisher',
            name='api_parameters',
        ),
        migrations.AddField(
            model_name='api',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publisherapi.Publisher'),
        ),
    ]
