# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-03-04 10:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publisherapi', '0006_user_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
