# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-03-02 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publisherapi', '0004_auto_20210222_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='token',
            field=models.CharField(default='', max_length=100),
        ),
    ]
